name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Unit tests
        run: go test ./internal/...

      - name: Integration tests
        run: go test -v -timeout 5m ./test/integration/...
        env:
          ZITI_VERSION: latest
